In [ ]:
import numpy as np


https://www.w3resource.com/python-exercises/numpy/python-numpy-stat.php

Write a Python program to find the maximum and minimum value of a given flattened array.

In [ ]:
arr = np.array([[3, 0], [1, 2]])
print(arr.max())
print(arr.min())

3
0


Write a NumPy program to get the minimum and maximum value of a given array along the second axis.

In [ ]:
arr = np.array([[3, 0], [1, 2]])
print("Max: ", arr.max(axis=0))
print("Min: ", arr.min(axis=0))

Max:  [3 2]
Min:  [1 0]


Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.

In [ ]:
arr = np.array([[3, 0], [1, 2]])
print("Difference between max and min", arr.max(axis=0)-arr.min(axis=0))

Difference between max and min [2 2]


Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.

In [ ]:
arr = np.array([[0, 3, 4], [5, 2, 1]])
print("80th Percentile", np.percentile(arr, 80, axis=1))

80th Percentile [3.6 3.8]


Write a NumPy program to compute the median of flattened given array.

In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

median = np.percentile(data, 50)
print("Median:", median)

q25, q75 = np.percentile(data, [25, 75])
print("25th Percentile:", q25)
print("75th Percentile:", q75)

Median: 5.5
25th Percentile: 3.25
75th Percentile: 7.75


Write a NumPy program to compute the weighted of a given array.


In [ ]:
data = np.array([0,1,2,3,4])
x = np.arange(len(data))+1
print((x*(data/data.sum())).sum())

2.666666666666667


Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.

In [ ]:
data = np.array([[3, 0], [1, 2]])

print("Mean:", data.mean(axis=1))
print("Std: ", data.std(axis=1))
print("Variance: ", np.var(data, axis=1))

Mean: [1.5 1.5]
Std:  [1.5 0.5]
Variance:  [2.25 0.25]


Write a NumPy program to compute the covariance matrix of two given arrays. Covariance is a statistical term that refers to a systematic relationship between two random variables in which a change in the other reflects a change in one variable.

In [ ]:
a = np.array([0, 1, 2])
b = np.array([2, 1, 0])
print("Covariance: ", np.cov(a, b))

Covariance:  [[ 1. -1.]
 [-1.  1.]]


Write a NumPy program to compute cross-correlation of two given arrays.

In [ ]:
a = np.array([0, 1, 3])
b = np.array([2, 4, 5])
print("Cross corralation: ", np.correlate(a, b))

Cross corralation:  [19]


Write a NumPy program to compute pearson product-moment correlation coefficients of two given arrays.

In [ ]:
a = np.array([0, 1, 3])
b = np.array([2, 4, 5])
print("Product moment correlation: ", np.corrcoef(a, b))

Product moment correlation:  [[1.         0.92857143]
 [0.92857143 1.        ]]


Compute the outer product of two given vectors


In [ ]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("Outer product: ", np.outer(p, q))

Outer product:  [[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


Compute the inner product of vectors for 1-D arrays and in higher dimension

In [ ]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("Inner product: ", np.inner(p, q))

Inner product:  [[1 3]
 [2 4]]


Compute the determinant of a matrix



> Indented block



In [ ]:
q = [[1, 2], [3, 4]]
print("Determinant of matrix: ", np.linalg.det(q))

Determinant of matrix:  -2.0000000000000004


Compute the inverse of a given matrix

In [ ]:
q = [[1, 2], [3, 4]]
print("Inverse of matrix: ", np.linalg.inv(q))

Inverse of matrix:  [[-2.   1. ]
 [ 1.5 -0.5]]


Find a matrix or vector norm

In [ ]:
q = [[1, 2], [3, 4]]
print("Norm of matrix: ", np.linalg.norm(q))

Norm of matrix:  5.477225575051661


Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.



In [ ]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=str)

capitalized_case = np.char.capitalize(x)
print("\nCapitalized: ", capitalized_case)
lowered_case = np.char.lower(x)
print("Lowered: ", lowered_case)
uppered_case = np.char.upper(x)
print("Uppered: ", uppered_case)
swapcased_case = np.char.swapcase(x)
print("Swapcased: ", swapcased_case)
titlecased_case = np.char.title(x)
print("Titlecased: ", titlecased_case)



Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


Write a NumPy program to make the length of each element 15 of a given array and the string centered / left-justified / right-justified with paddings of _.



In [ ]:
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=str)
centered = np.char.center(x, 15, fillchar='_')
print("\nCentered =", centered)
left = np.char.ljust(x, 15, fillchar='_')
print("Left =", left)
right = np.char.rjust(x, 15, fillchar='_')
print("Right =", right)


Centered = ['python exercise' '______PHP______' '______java_____' '______C++______']
Left = ['python exercise' 'PHP____________' 'java___________' 'C++____________']
Right = ['python exercise' '____________PHP' '___________java' '____________C++']


Write a NumPy program to insert a space between characters of all the elements of a given array.



In [ ]:
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=str)
print(np.char.join(" ", x))

['p y t h o n   e x e r c i s e s' 'P H P' 'j a v a' 'C + +']


Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array.



In [ ]:
x = np.array(['    python exercises  ', ' PHP', '  java', 'C++  '], dtype=str)
print("Remove the leading and trailing whitespaces:\n", np.char.strip(x))

Remove the leading and trailing whitespaces:
 ['python exercises' 'PHP' 'java' 'C++']


Write a NumPy program to split the element of a given array to multiple lines.



In [ ]:
x = np.array(['python exercises\nPHP\n', 'java\n\nC++'], dtype=str)
print(np.char.splitlines(x))

[list(['python exercises', 'PHP']) list(['java', '', 'C++'])]


Write a NumPy program to replace "PHP" with "Python" in the element of a given array.



In [ ]:
x = np.array(['python exercises', 'PHP', 'java', 'C++'], dtype=str)
print(np.char.replace(x, "PHP", "Python"))

['python exercises' 'Python' 'java' 'C++']


Write a NumPy program to count the number of "P" in a given array, element-wise.



In [ ]:
x = np.array(['python exercises', 'php', 'java', 'C++'], dtype=str)
print(np.char.count(x,  "p"))

[1 2 0 0]


Write a NumPy program to check whether each element of a given array is composed of digits only, lower case letters only and upper case letters only.



In [ ]:
x = np.array(['python exercises', 'PHP', 'Js', '5', '126' 'java', 'C++'], dtype=str)
print("Check a given array is composed of digits only:\n", np.char.isdigit(x))
print("Check a given array is composed of lower letters only:\n", np.char.islower(x))
print("Check a given array is composed of upper letters only:\n", np.char.isupper(x))

Check a given array is composed of digits only:
 [False False False  True False False]
Check a given array is composed of lower letters only:
 [ True False False False  True False]
Check a given array is composed of upper letters only:
 [False  True False False False  True]


Write a NumPy program to check whether each element of a given array starts with "P".



In [ ]:
x = np.array(['python exercises', 'PHP', 'Js', '5', '126' 'java', 'C++'], dtype=str)
print("Check a given array is start with 'P':\n", np.char.startswith(x, "P"))


Check a given array is start with 'P':
 [False  True False False False False]
